<?php 
include '../includes/header.php'; 
require_once '../config/db_model.php';

$getAllMenuItems = fetch('menu', '', 'is_best_seller DESC, name ASC');
$menuItems = $getAllMenuItems;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu - Ellen's Food House</title>
    <link rel="stylesheet" href="../assets/css/menu.css">
</head>
<body>

<!-- Main Menu Content -->
<main class="main-content">
    <?php if (!empty($menuItems)): ?>
    <section class="menu-section">
        <div class="container">
            <h2 class="section-title">Our Menu</h2>
            
            <!-- Search and Filter Controls -->
            <div class="menu-controls">
                <div class="search-container">
                    <input type="text" id="searchInput" placeholder="Search menu items..." class="search-input">
                    <i class="fas fa-search search-icon"></i>
                </div>
                
                <div class="filter-container">
                    <button class="filter-btn active" data-filter="all">
                        <i class="fas fa-th-large"></i> All Items
                    </button>
                    <button class="filter-btn" data-filter="best-seller">
                        <i class="fas fa-star"></i> Best Sellers
                    </button>
                    <button class="filter-btn" data-filter="regular">
                        <i class="fas fa-utensils"></i> Regular Items
                    </button>
                </div>
            </div>
            
            <!-- No Results Message -->
            <div id="noResults" class="no-results" style="display: none;">
                <i class="fas fa-search"></i>
                <h3>No items found</h3>
                <p>Try adjusting your search or filter criteria</p>
            </div>
            
            <div class="menu-grid" id="menuGrid">
                <?php foreach ($menuItems as $index => $item): ?>
                    <div class="menu-item <?php echo $item['is_best_seller'] ? 'featured best-seller' : 'regular'; ?>" 
                         data-name="<?php echo strtolower(htmlspecialchars($item['name'])); ?>"
                         data-category="<?php echo $item['is_best_seller'] ? 'best-seller' : 'regular'; ?>"
                         data-index="<?php echo $index; ?>">
                        <?php if ($item['image_path']): ?>
                            <div class="item-image" onclick="openModal('<?php echo htmlspecialchars($item['image_path']); ?>', '<?php echo htmlspecialchars($item['name']); ?>', '<?php echo number_format($item['price'], 2); ?>')">
                                <img src="../uploads/menu/<?php echo htmlspecialchars($item['image_path']); ?>" 
                                     alt="<?php echo htmlspecialchars($item['name']); ?>">
                                <?php if ($item['is_best_seller']): ?>
                                    <div class="bestseller-badge">Best Seller</div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <div class="item-content">
                            <h3 class="item-name"><?php echo htmlspecialchars($item['name']); ?></h3>
                            <p class="item-price">₱<?php echo number_format($item['price'], 2); ?></p>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            
            <!-- Pagination -->
            <div class="pagination-container" id="paginationContainer">
                <div class="page-info">
                    <span id="pageInfo">Showing 1-16 of <?php echo count($menuItems); ?> items</span>
                </div>
                <ul class="pagination" id="pagination">
                    <!-- Pagination will be generated by JavaScript -->
                </ul>
            </div>
        </div>
    </section>
    <?php endif; ?>

    <?php if (empty($menuItems)): ?>
    <section class="menu-section">
        <div class="container">
            <div class="empty-menu">
                <h2>Menu Coming Soon</h2>
                <p>We're working on bringing you an amazing menu experience.</p>
            </div>
        </div>
    </section>
    <?php endif; ?>
</main>

<!-- Image Modal -->
<div id="imageModal" class="image-modal">
    <span class="modal-close" onclick="closeModal()">&times;</span>
    <div class="modal-content">
        <img id="modalImage" src="" alt="">
        <div class="modal-caption">
            <h3 id="modalTitle"></h3>
            <div class="price" id="modalPrice"></div>
        </div>
    </div>
</div>

<?php include '../includes/footer.php'; ?>

<!-- Add FontAwesome if not already included -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

<!-- Menu JavaScript -->
<script src="../assets/js/menu.js"></script>
</body>
</html>
